### ISSUE TITLE
db must be initialized before connection

### ISSUE THREAD

**Issue by havok2063** [sdss/valis#32]
With the recent updates after #25, I now get the following error `Error, database must be initialized before opening a connection.` when trying to run any valis endpoint that uses the database.  In production, this error occurs every time.  In development, this error occurs only the first time.  My guess is due to the config `db_reset: false`.  Pinging @albireox. 

This returns an internal server error, but inspecting the container logs shows the full traceback below. 
```
curl -X 'GET' \
  'https://api.sdss.org/valis/info/database?schema=targetdb&release=IPL3' \
  -H 'accept: application/json'
```

Full traceback
```
[2024-07-30 16:59:08 +0000] [5] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/tmp/python/valis/routes/info.py", line 146, in get_dbmetadata
    return convert_metadata(get_db_metadata(schema=schema).dicts().iterator())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2102, in iterator
    return iter(self.execute(database).iterator())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2025, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2096, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2269, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3319, in execute
    return self.execute_sql(sql, params)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3310, in execute_sql
    cursor = self.cursor()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3303, in cursor
    return self._state.conn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 14, in __call__
    async with AsyncExitStack() as stack:
  File "/usr/local/lib/python3.10/contextlib.py", line 714, in __aexit__
    raise exc_details[1]
  File "/usr/local/lib/python3.10/contextlib.py", line 697, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/fastapi/concurrency.py", line 31, in contextmanager_in_threadpool
    await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/tmp/python/valis/db/db.py", line 81, in get_pw_db
    db.close()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3267, in close
    raise InterfaceError('Error, database must be initialized '
peewee.InterfaceError: Error, database must be initialized before opening a connection.
```

**Comment by albireox** [comment]
Mmm, that's unfortunate. I tried it really quickly and it worked for me. My `.valis` configuration is

```yaml
allow_origin: ['http://localhost:3000']
db_remote: true
db_port: 7602
db_user: u0931042
db_server: null
db_reset: false
```

I'm traveling today but I should be able to have a closer look at this tonight.

**Comment by havok2063** [comment]
No worries.  Yes, my config is very similar
```
allow_origin: ['http://localhost:3000']
db_remote: true
db_port: 6000
db_user: u0857802
db_server: null
db_reset: false
```
In development mode, once starting valis, if I use valis directly it works ok.  If I use zora first I see the error in the console, but after I use valis a second time, everything works.  In production, which does not have `db_reset` set at all, valis gives the error every time.

**Comment by albireox** [comment]
OK, I think I can reproduce this but no clue yet as to the exact cause. What it seems to happen is that when you launch Zora the connection fails to open. But if you do a curl query that seems to open the connection properly and from that point on Zora works fine.

I suspect the problem may be with the concurrent queries that Zora does here

https://github.com/sdss/zora/blob/e4a6d8c9122df14e76a0c37b116cbf42e5c6cfda/src/views/Target.vue#L179

which may all be trying to race to create a connection.

**Comment by havok2063** [comment]
In production mode, I can't do any valis queries at all, ignoring zora altogether.  For example, this query https://api.sdss.org/valis/docs#/info/get_dbmetadata_info_database_get is a lightweight query that only pulls metadata from the database.   Repeated tries never seem to open the connection properly.

**Comment by havok2063** [comment]
You can test the production mode locally with 
```
export VALIS_WORKERS=2
mkdir -p /tmp/valis
gunicorn -c python/valis/wsgi_conf.py valis.wsgi:app
```
and setting `db_reset: true`.  I think the connection is constantly getting reset and never correctly reopens on a new request.

**Comment by albireox** [comment]
Can you give #34 a try? I'm not sure that I fully understand what is happening but it seems related to the `ContextVar` that you added to set the Peewee connection state and the fact that I had removed the fastapi dependency. I've added the dependency back and now check if `db_reset` is True inside the dependency and that seems to work for me, but I may not have tested all the cases that you mentioned.

**Comment by albireox** [comment]
#34 seems to fix this.
